name: CI/CD Pipeline

on:
  #   push:
  #     branches:
  #       - main
  workflow_dispatch: # Allows manual execution

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: rag-api
  AWS_ROLE_ARN: arn:aws:iam::489582127457:role/GitHubActionsRole

permissions:
  id-token: write # Required for OIDC
  contents: read # Required to checkout code

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
        image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rag-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Render and Deploy ECS Task Definition
        run: |
          aws ecs register-task-definition --cli-input-json file://task-definition.json
          aws ecs update-service --cluster beloved-wolf-0mjus8 --service fastapi_accip-api-service-fb4p9ip1 --force-new-deployment
        env:
          AWS_REGION: ap-south-1
