name: Ollama Model Build and Push to ECR

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Allows manual execution

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: ollama
  AWS_ROLE_ARN: arn:aws:iam::489582127457:role/GitHubActionsRole
  DOCKER_FILE: Dockerfile.ollama

permissions:
  id-token: write # Required for OIDC
  contents: read # Required to checkout code

jobs:
  build-ollama:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Ollama Docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -f ${{ env.DOCKER_FILE }} -t $ECR_REGISTRY/$ECR_REPOSITORY .
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY" >> $GITHUB_OUTPUT
          echo "Built Ollama image: $ECR_REGISTRY/$ECR_REPOSITORY"

      # Skip testing for now - Ollama takes too long to initialize in CI
      # You can test the container manually after deployment
      - name: Verify Docker image was built
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "Verifying image was built successfully..."
          docker images | grep $ECR_REPOSITORY
          echo "Image build completed successfully!"

      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY
          echo "Pushed Ollama image to ECR: $ECR_REGISTRY/$ECR_REPOSITORY"

      - name: Save image URI as artifact
        run: |
          echo "${{ steps.build-image.outputs.image }}" > ollama-image-uri.txt
          echo "Saved Ollama image URI: $(cat ollama-image-uri.txt)"

      - name: Upload image URI artifact
        uses: actions/upload-artifact@v4
        with:
          name: ollama-image-uri
          path: ollama-image-uri.txt
          retention-days: 7
